#!/system/bin/sh
#/*
# * Portions copyright 2009-2014 Paragon Software GmbH
# * $Author: Ivan.Zorin $
# * Support: oem@paragon-software.com
# * License: This code is licensed under the associated license agreement.
# *
# * ----- Disclaimer ------
# * Paragon Software accepts no responsibility for malfunctions or damage caused
# * by modification of the software or the use of the software in conjunction with
# * hardware configurations, platforms or operating systems other than the
# * recommended or intended hardware configuration, platform or operating system.
# *
# * Copyright (C) 2008 The Android Open Source Project
# * Copyright (C) 2014 Paragon Software GmbH
# *
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.apache.org/licenses/LICENSE-2.0
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *
# * NOTE: This file has been modified by Paragon Software Group GmbH.
# * Modifications are licensed under the License.
# */

test -f /system/lib/modules/jnl.ko && insmod /system/lib/modules/jnl.ko
insmod /system/lib/modules/ufsd.ko

